### ISSUE TITLE
Testing Conventions

### ISSUE THREAD

**Issue by davesims** [kubostech/kubos-cli#4]
We need to decide on the best way forward for unit testing on this repo. Currently looking at:

* http://docs.pytest.org/en/latest/
* https://github.com/nose-devs/nose2

@kyleparrott @plauche Any preferences?

**Comment by kyleparrott** [comment]
I don't have any major preferences. While you're investigating these frameworks check out Tox too: https://tox.readthedocs.io/en/latest/index.html

**Comment by davesims** [comment]
Good discussion here: https://www.reddit.com/r/Python/comments/3ys29v/nose_alternatives_nose2_pytest_or_something_else/

**Comment by kyleparrott** [comment]
That's interesting. The only benefit of Tox I see, is that it supports virtual environments and testing in multiple python installations out of the box. But since we only support python 2.7 I don't know how much we care about that (I think not at all).

I like pytest just because that's what I'm most familiar with but nose2 looks like it has some interesting advantages. I'll let you decide @davesims.

**Comment by davesims** [comment]
Going with pytest for now. Tox can work with it, they're not mutually exclusive. Closing this and moving forward with pytest.
